version: '3'

services:   
  db:
    image: postgis/postgis:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: FigureFinder
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: